export const SIGNIN_USER = 'SIGNIN_USER';
export const SIGNIN_USER_SUCCESS = 'SIGNIN_USER_SUCCESS';
export const SIGNIN_USER_FAILURE = 'SIGNIN_USER_FAILURE';

export const SIGNUP_USER = 'SIGNUP_USER';
export const SIGNUP_USER_SUCCESS = 'SIGNUP_USER_SUCCESS';
export const SIGNUP_USER_FAILURE = 'SIGNUP_USER_FAILURE';

export const CONFIRM_REGISTER = 'CONFIRM_REGISTER';
export const CONFIRM_REGISTER_SUCCESS = 'CONFIRM_REGISTER_SUCCESS';
export const CONFIRM_REGISTER_FAILURE = 'CONFIRM_REGISTER_FAILURE';

export const REMEMBER_PASSWORD = 'REMEMBER_PASSWORD';
export const REMEMBER_PASSWORD_SUCCESS = 'REMEMBER_PASSWORD_SUCCESS';
export const REMEMBER_PASSWORD_FAILURE = 'REMEMBER_PASSWORD_FAILURE';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_SUCCESS = 'RESET_PASSWORD_SUCCESS';
export const RESET_PASSWORD_FAILURE = 'RESET_PASSWORD_FAILURE';

export const SIGNOUT = 'SIGNOUT';
export const SIGNOUT_SUCCESS = 'SIGNOUT_SUCCESS';
export const SIGNOUT_FAILURE = 'SIGNOUT_FAILURE';

export const CHANGE_TAB = 'CHANGE_TAB';

export const CLEAR_STATE = 'CLEAR_STATE';